# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale: "en-US"
title: "Posts"
title_separator: "-"
description: "Pedro Carneiro's posts"
author: "Pedro Carneiro"
github: "https://github.com/pedro-carneiro"
about: "A backend developer that usually writes Java."
url: "https://blog.pcarneiro.com"
baseurl: ""
repository: "pedro-carneiro/pedro-carneiro.github.io"
words_per_minute: 200
disqus_shortname: "pedro-carneiro-posts"
google_analytics: # UA-XXXXXXXX-Y

enableTags: true
tagarray: []

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/pedrocarneiro/"
    - icon: fa-stack-overflow
      link: "https://stackoverflow.com/users/558825/pedro-carneiro"
    - icon: fa-github
      link: "https://github.com/pedro-carneiro"

share:
  twitter_username: # github.io

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: "/:year/:month/:title.html"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
timezone: Europe/Lisbon # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-gist

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-gist


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
